### ISSUE TITLE
[BUG] agent-base is breaking got

### ISSUE THREAD

**Issue by yovanoc** [npm/make-fetch-happen#17]
Hello

node-agent-base < 5 is modifying a core method of nodejs. Which make got unusable.
I use lerna to manage a yarn workspaces monorepo, and I deep down until I found you.

If you could upgrade to the version 5 it would be very helpful for a lot of people like me who use got on the yarn workspaces. Thanks

![image](https://user-images.githubusercontent.com/7302317/73123084-19db5f80-3f8c-11ea-8e22-d29af8544a78.png)

You could look at this to a better understanding.

https://github.com/sindresorhus/got/issues/951

**Comment by yovanoc** [comment]
Please any news on this, it's really breaking... you just have to upgrade these 3 proxy agent to the latest version..

**Comment by Raphael0010** [comment]
Hi, anyone got some news about this error ? I got this one too.
