### ISSUE TITLE
Alternative cache storages

### ISSUE THREAD

**Issue by thewilkybarkid** [npm/make-fetch-happen#215]
I never used them, but the library used to have a mechanism for using different caching backends. In #49 this was removed; reading the PR, it seems this was a side-effect of improving the overall feature. I haven't yet explored what changes would need to be made, but would you allow for other cache storages to be accepted as a feature?

I'm using the library in a Node app hosted on [Fly.io](https://fly.io/), which creates a new instance on every deployment. This means a trade-off between having an empty cache (could be 10, 20 times a day), or mounting a volume to persist them (which brings its own tradeoffs and limitations, and can't be shared between multiple instances). Ideally, I'd like to separate the app from its cache entirely (e.g. using Redis). The make-fetch-happen cache has been working great, and I'm trying to avoid going down the road of running a forward proxy.

**Comment by nlf** [comment]
we were unaware of anyone who was actually using the custom cache interface. that said, if one were designed and submitted by our community, i would be happy to review and land it!

**Comment by wraithgar** [comment]
We're trying to be more curative about the issue we leave open here.   Feature requests, unless they're something on our current active roadmap, aren't being kept open.  Folks who want features are welcome to submit PRs for them (we've landed a LOT of backlogged ones the past few weeks, and look forward to more).
