### ISSUE TITLE
Backport non-breaking security-related fixes to v10

### ISSUE THREAD

**Issue by legobeat** [npm/make-fetch-happen#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`make-fetch` `v10` is exposed to several issues through its dependencies. (#210, among others).

`make-fetch` `v11` fixes these, but breaks compatibility with Node.js v12 through bumps of `cacache` (#184) `minipass-fetch` (#186), and `ssri` (#187).

### Expected Behavior

While Node.js v12 is EoL as of 2022-04-30, several ecosystem packages still indicate support for it in their mainline versions.

Releasing a non-breaking backport 10.x release addressing security issues and subdependency deprecation (to reasonable extent) would be very helpful and provide protection for users who are yet to update (perhaps because they are using node-gyp...).

It would also make it more straightforward for lagging dependent packages to make the move off Node 12 themselves.

### Steps To Reproduce

n/a

### Environment

n/a

**Comment by wraithgar** [comment]
```sh
$ npm i make-fetch-happen@10
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 68 packages, and audited 69 packages in 2s

found 0 vulnerabilities
~/D/n/s/mfh $ npm audit
found 0 vulnerabilities
```

What vulnerabilities?  Package-lock entries are not really vulnerabilities as they do not affect what the user will get when they install a module in their own project.

**Comment by wraithgar** [comment]
Typically we don't bump semver ranges in a package.json to clear security vulnerabilities.  The semver range allows for the fix, and folks can run their own audits.  The v11 bump of http-cache-semantics was not normal.

We don't currently plan on backporting fixes to v10 here, given the imminent EOL of node12 and the fact that the semver ranges in v10 allow for an install with no vulnerabilities.

I don't know of any other "non-breaking security related fixes" this module got.  The file permissions change was a breaking change and can't be backported.  Looking at the changelog it's all dependency updates and a change to allow configurable cached headers.

**Comment by wraithgar** [comment]
I'm sorry but maybe I'm not seeing where the issue is, there are a lot of comments sprinkled now through half a dozen repos.  If there are package declarations in v10 that have engines declarations that are out of band with the engines declaration in this module that's actionable. I don't see that as the case currently and that is one of the things we check during our CI via template-oss "check engines" step.
