### ISSUE TITLE
[FEATURE] defaults() should do deep defaulting of headers

### ISSUE THREAD

**Issue by tcort** [npm/make-fetch-happen#25]
# What / Why

In `defaultedFetch` in `index.js` ([src](https://github.com/npm/make-fetch-happen/blob/latest/index.js#L44)), the defaulting is done with `Object.assign({}, _opts || {}, opts || {})`

This is a problem if `headers` are specified in the defaults *and* the invocation because the default `headers` object gets overridden.

## When

* n/a

## Where

* n/a

### Current Behavior

Take this example:

```
const customFetch = fetch.defaults({
    headers: {
        'X-Request-Id': uuid.v3(),
    }
});

customFetch(url, {
    headers: {
        Accept: 'application/json'
    }
}).then(...);
```
`Accept` is sent with the request but not `X-Request-Id`.

### Expected Behavior

Using the example above, I expect both `X-Request-Id` and `Accept` to be included in the headers sent with the request.

## Who

* n/a

## References

* n/a

**Comment by monkey-jeff** [comment]
This would be an incredibly useful feature for us as well.
