### ISSUE TITLE
[QUESTION] Does ECONNRESET retry or not? Documentation says yes and no.

### ISSUE THREAD

**Issue by davidtheclark** [npm/make-fetch-happen#27]
# What / Why

In the readme I see these two statements that seem contradictory:

> Retries will only be attempted on the following conditions ... Request errored with ECONNRESET ...

> The following are worth noting as explicitly not retried ... ECONNRESET currently has no support for restarting. ...

Is one of these a mistake? Or is "restarting" different than "retrying", and I'm not understanding?

From [this code](https://github.com/npm/make-fetch-happen/blob/c389a1e567327359aa4b34dbf805989ecbd9755b/index.js#L21-L28) it looks like `ECONNRESET` should be treated the same way as other connection errors. I'm hoping that's the case, and the second statement above is a mistake 😬

**Comment by bcole** [comment]
I am researching the same question, did you ever find an answer @davidtheclark ?
