### ISSUE TITLE
5.1.0

### ISSUE THREAD

**Issue by JamesKyburz** [npm/make-fetch-happen#3]
The changelog doesn't mention release 5.1.0. 

Was 5.1.0 released by mistake and is the same as 6.0.0?

**Comment by JordanBonitatis** [comment]
Hoping on here. I think 5.1.0 introduced a breaking change. I filed a bug for it here: https://github.com/lerna/lerna/issues/2298

**Comment by isaacs** [comment]
Yes, that is correct.

**Comment by isaacs** [comment]
(It's since been unpublished.)
