### ISSUE TITLE
[BUG] Vulnerability in 2.x line

### ISSUE THREAD

**Issue by jcardali** [npm/make-fetch-happen#42]
There are several high severity vulnerabilities in the current version of `https-proxy-agent` permitted by the 2.x line

- https://github.com/advisories/GHSA-pc5p-h8pf-mvwp
- https://github.com/nodejs/security-wg/blob/master/vuln/npm/505.json
- https://cwe.mitre.org/data/definitions/300.html
- https://github.com/nodejs/security-wg/blob/master/vuln/npm/388.json

The fix is very simple (bumping from ^2.1.0 to ^2.2.0), but is addressing this even a possibility given the current version is 8.x?

**Comment by nlf** [comment]
closing since we're using the 5.x releases now
