### ISSUE TITLE
Snyk reports MitM vulnerability for https-proxy-agent@2

### ISSUE THREAD

**Issue by spurreiter** [npm/make-fetch-happen#5]
Snyk reports MitM vulnerability for https-proxy-agent@2 at https://snyk.io/test/npm/https-proxy-agent/2
Could you please upgrade to version https-proxy-agent@3 ?

**Comment by ricksmt** [comment]
This vulnerability has made it to NPM's advisory list: [1184](https://www.npmjs.com/advisories/1184).

**Comment by isaacs** [comment]
Fixed on v5 and latest.  Thanks!
