### ISSUE TITLE
[BUG] CHANGELOG.md doesn't document version 9.x.x

### ISSUE THREAD

**Issue by tcort** [npm/make-fetch-happen#51]
# What / Why

Version 9.0.0 was published recently. According to [semver](https://semver.org/), a major version bump indicates a breaking change. Neither `CHANGELOG.md` nor `README.md` describe what has changed.

## When

* when v9.0.0+ was released

## Where

  * npm/make-fetch-happen

## How

* nobody documented the change

### Current Behavior

* Change log only describes up to version 8.0.3

### Steps to Reproduce

* Look here: https://github.com/npm/make-fetch-happen/blob/latest/CHANGELOG.md

### Expected Behavior

* See what changed so that I know if my code will break or not when I upgrade.

## Who

* n/a

## References

* n/a

**Comment by nlf** [comment]
i added 9.0.0, 9.0.2 and 9.0.3 today with the release of 9.0.3 (9.0.1 was pretty insignificant, so skipped)
