### ISSUE TITLE
Remove the mention of a custom cache from README.md if it's no longer supported

### ISSUE THREAD

**Issue by coolov** [npm/make-fetch-happen#61]
# What / Why
Describe how to use the custom cache API if it's still supported. Or if it's no longer supported, remove the mentions of it from README.md.

### Current Behavior
- There is a section in the README.md that shows the usage of Redis as a custom cache, but it doesn't show how to pass the custom cache implementation to fetch:
https://github.com/npm/make-fetch-happen#example-3
- There is a PR that indicates that the custom cache interface is no longer supported:
https://github.com/npm/make-fetch-happen/pull/49

### Expected Behavior
A README.md that is consistent with the supported API.

**Comment by kevinlul** [comment]
Why was it hardcoded to cacache? This was very confusing navigating this and what I assume is the old @zkat repository.
