### ISSUE TITLE
[BUG] https-proxy-agent vulnerability 

### ISSUE THREAD

**Issue by seanBucholtz** [npm/make-fetch-happen#8]
# What / Why
npm vulnerability report shows make-fetch-happen package having a dependency on https-proxy-agent@2.2.1 which is affected by a machine-in-the-middle vulnerability.

![image](https://user-images.githubusercontent.com/8270017/67254170-7fb9c780-f430-11e9-8507-c87d664d7dc5.png)

## When
October 21, 2019

## Where
* n/a

## How
* n/a

### Current Behavior
* n/a

### Steps to Reproduce
* npm audit

### Expected Behavior
* n/a

## Who
* n/a

## References
[NPM advisory](https://www.npmjs.com/advisories/1184)

**Comment by delps1001** [comment]
Why was this issue closed? was the bug fixed?

**Comment by seanBucholtz** [comment]
Hi,

I noticed that there is already an open pull request addressing the same underlying issue, so I thought it was probably best to close the one I created.

Cheers,


Sean Bucholtz | Software Development Engineer
+1 (206) 854-3993
sean.bucholtz@gmail.com
Seattle, WA U.S.A.

**Comment by TheGreatRefrigerator** [comment]
@seanBucholtz as long as the pull request is not merged i would keep this open as it is still an issue.
